### ISSUE TITLE
Hanging on the loading page of the demo/app.py

### ISSUE THREAD

**Issue by Deathn0t** [clement-pages/gryannote#108]
Dear @clement-pages ,

Your package looks very nice. However, when I tried to use it the server starts after running `python demo/app.py` but when I open the browser it remains stuck on the "Loading..." page with the Gradio logo.

I tried reproducing the environment of the space you have with Python 3.11, using the same requirements.txt file and using the same grade SDK 4.27.0 but it is still stuck.

Would you have any idea about how to resolve that?

Thank you so much.

**Comment by clement-pages** [comment]
Hey @Deathn0t ,

Thank you for using `gryannote`. I'll need more information to try to solve the issue:
- which browser do you use?
- Can you send  the browser logs when you try to launch gryannote?

My first intuition is that it looks like a problem with the installation of at least one of the components that isn't found by the server, leading to an error when the page is loading.

**Comment by Deathn0t** [comment]
I am attaching the logs when opening the server:

<img width="1458" alt="Capture d’écran 2024-12-06 à 13 52 18" src="https://github.com/user-attachments/assets/6d3aeda6-2ef1-4a46-9c27-847715c6934b">

**Comment by clement-pages** [comment]
Thanks for the logs. I think there is an issue with your installation as the server cannot find components files. Maybe try to reinstall `gryannote` from scratch. 

On my side, I've just launched `gryannote` on Chorme (131.0.6778.108) but I was not able to reproduce the issue, and the interface loads properly.

**Comment by Deathn0t** [comment]
I tried it on a different laptop (both on macos) and it worked (i.e., the interface loaded properly). I will see if I can make it work on the initial laptop and keep you posted if I understand what went wrong.

**Comment by Deathn0t** [comment]
Maybe my issue what due to installing the package in "editable mode":
1. pulling main branch
2. `pip install -e "."`

After forcing the reinstallation from Python 3.12, and running `pip install -I gryannote` the dashboard loads well.
